language: erlang
before_script: "sudo apt-get install -y avahi-daemon libavahi-compat-libdnssd-dev && sudo service avahi-daemon start"
otp_release:
   - R14B04
   - R14B03
   - R14B02
   - R14B01
   - R14B
   - R14A
   - R13B04
   - R13B03